#!/usr/bin/env bash
# Bucket-count sweep for sklib's sorted super-k-mer list (the new VSKMER_3 format).
#
# Holds (dataset,k,m) fixed and varies --buckets, to expose how the per-bucket directory
# trades space (bits/k-mer total vs payload) against construction and query cost. Reuses the
# main harness primitives (lib.sh / tools.sh) and the query workloads already generated by
# bench.sh, so it must run AFTER a bench.sh run that covered the dataset at this k.
#
# Output: scripts/out/bench/results_buckets.csv (own schema, with a `buckets` column).
#
# Env knobs (defaults): DATASET=ecoli K=21 M=11 BUCKETS_LIST="1 64 1024 4096 65536" REPS=3
set -uo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
BENCH_REPO_ROOT="$(cd -- "$SCRIPT_DIR/../.." && pwd)"
cd "$BENCH_REPO_ROOT"
source "$SCRIPT_DIR/lib.sh"
source "$SCRIPT_DIR/tools.sh"

DATASET="${DATASET:-ecoli}"
K="${K:-21}"
M="${M:-11}"
BUCKETS_LIST="${BUCKETS_LIST:-1 64 1024 4096 65536}"
REPS="${REPS:-3}"

OUT="$BENCH_REPO_ROOT/scripts/out/bench"
QDIR="$OUT/queries"
WORK="$OUT/work"
CSV="$OUT/results_buckets.csv"
mkdir -p "$WORK" "$BENCH_KMC_TMP"

available_sklib || { echo "sskm not built at $SSKM_BIN" >&2; exit 1; }
prepare_genome "$DATASET" || { echo "cannot resolve genome $DATASET" >&2; exit 1; }
san="$SAN"

qbase="$QDIR/$DATASET.$K"
for wl in positive random; do
    [[ -f "$qbase.$wl.fa" && -f "$qbase.$wl.nq" ]] || {
        echo "missing query set $qbase.$wl.fa -- run bench.sh on $DATASET k=$K first" >&2; exit 1; }
done

log "bucket sweep: $DATASET k=$K m=$M buckets=[$BUCKETS_LIST] reps=$REPS"
distinct="$(kmc_distinct_count "$san" "$K")"
log "distinct canonical $K-mers: $distinct"

CSV_HEADER="buckets,distinct_kmers,n_superkmers,index_bytes,header_bytes,payload_bytes,bits_per_kmer_payload,bits_per_kmer_total,construct_s,construct_rss_kb,qpos_s,qpos_rss_kb,qpos_Mkmer_s,qrand_s,qrand_rss_kb,qrand_Mkmer_s"
echo "$CSV_HEADER" > "$CSV"

nqp="$(cat "$qbase.positive.nq")"
nqr="$(cat "$qbase.random.nq")"

for B in $BUCKETS_LIST; do
    log "--- buckets=$B ---"
    wd="$WORK/bucketsweep_$B"; rm -rf "$wd"; mkdir -p "$wd"

    # Construction (BUCKETS env drives --buckets in construct_sklib; sets IDX_*/N_SKMERS + timing).
    BUCKETS="$B" construct_sklib "$san" "$K" "$M" "$wd" || { warn "construct failed at buckets=$B"; continue; }
    c_s="$RUN_SEC"; c_rss="$RUN_RSS_KB"
    hdr=$(( IDX_FILE_BYTES - IDX_PAYLOAD_BYTES ))
    bits_p="$(bits_per_kmer "$IDX_PAYLOAD_BYTES" "$distinct")"
    bits_t="$(bits_per_kmer "$IDX_FILE_BYTES" "$distinct")"

    # Queries (median over REPS, pinned to CPU 0), reusing the main run's workload files.
    RUN_REPS="$REPS"
    query_sklib "$IDX_PATH" "$qbase.positive.fa" "$K" "$M" 0
    qp_s="$RUN_SEC"; qp_rss="$RUN_RSS_KB"; qp_r="$(mrate "$nqp" "$qp_s")"
    query_sklib "$IDX_PATH" "$qbase.random.fa"   "$K" "$M" 0
    qr_s="$RUN_SEC"; qr_rss="$RUN_RSS_KB"; qr_r="$(mrate "$nqr" "$qr_s")"

    echo "$B,$distinct,$N_SKMERS,$IDX_FILE_BYTES,$hdr,$IDX_PAYLOAD_BYTES,$bits_p,$bits_t,$c_s,$c_rss,$qp_s,$qp_rss,$qp_r,$qr_s,$qr_rss,$qr_r" >> "$CSV"
    log "buckets=$B: index=$IDX_FILE_BYTES B (hdr=$hdr) payload bits/kmer=$bits_p total=$bits_t construct=${c_s}s/${c_rss}KB qpos=${qp_r}Mkmer/s qrand=${qr_r}Mkmer/s"
    rm -rf "$wd"
done

log "bucket sweep done -> $CSV"
column -t -s, "$CSV"
