name: CI Linux

on:
  push:
    branches: ["main","dev", "io"]
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        arch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment arm64
        if: matrix.arch == 'arm64'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++-aarch64-linux-gnu gcc-aarch64-linux-gnu qemu-user  libtbb-dev libbz2-dev

      - name: Setup environment x86_64 (intel and amd)
        if: matrix.arch == 'amd64'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang-18 libtbb-dev libbz2-dev

      - name: Install Google Test x86_64
        if: matrix.arch == 'amd64'
        run: |
          sudo apt-get install -y libgtest-dev
          cd /usr/src/gtest
          sudo cmake .
          sudo make
          sudo cp lib/*.a /usr/local/lib

      - name: Install Google Test on arm64
        if: matrix.arch == 'arm64'
        run: |
          # Create a toolchain file for cross-compilation
          cat > ~/toolchain-aarch64.cmake << 'EOF'
          set(CMAKE_SYSTEM_NAME Linux)
          set(CMAKE_SYSTEM_PROCESSOR aarch64)
          set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
          set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)
          set(CMAKE_FIND_ROOT_PATH /usr/aarch64-linux-gnu)
          set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
          set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
          set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
          EOF

          # Build Google Test for ARM64
          git clone https://github.com/google/googletest.git
          cd googletest
          mkdir build && cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=~/toolchain-aarch64.cmake -DCMAKE_INSTALL_PREFIX=/usr/aarch64-linux-gnu ..
          make -j$(nproc)
          sudo make install

      - name: Build arm64
        if: matrix.arch == 'arm64'
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=~/toolchain-aarch64.cmake -DCMAKE_BUILD_TYPE=DEBUG ..
          make -j$(nproc)

      - name: Build x86_64 (intel and arm)
        if: matrix.arch == 'amd64'
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=DEBUG \
                -DCMAKE_C_COMPILER=clang-18 \
                -DCMAKE_CXX_COMPILER=clang++-18 ..
          make -j$(nproc)

      - name: Cache Build
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-${{ matrix.arch }}-build-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.arch }}-build-

      - name: Run GTest on arm64
        if: matrix.arch == 'arm64'
        run: |
          cd build
          qemu-aarch64 -L /usr/aarch64-linux-gnu ./tests/sklib-tests

      - name: Run GTest on x86_64 (intel and arm)
        if: matrix.arch == 'amd64'
        run: |
          cd build
          ./tests/sklib-tests

